Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/xenial64"
config.vm.synced_folder "../shared", "/shared"
config.vm.provider "virtualbox" do |vb|
vb.memory = "4096"
vb.cpus = 4
end
config.disksize.size = '30GB'
config.ssh.forward_x11 = true
config.ssh.forward_agent = true
end
